# https://github.com/greshake/i3status-rust/blob/master/blocks.md

icons = "awesome" # none | awesome | material

# plain (default) | solarized-dark | solarized-light | slick | modern | bad-wolf
# gruvbox-light | gruvbox-dark
# Ƀ 
[theme]
name = "modern"

[theme.overrides]
idle_bg = "#00000033"
idle_fg = "#abcdef"

[[block]]
block = "custom"
command = "curl -s 'https://api.binance.com/api/v3/ticker/price?symbol=BTCUSDT' | jq -r .price | xargs printf \" %.*f\n\" \"$p\""
interval = 100

[[block]]
block = "custom"
on_click = "skippy-xd"
command = "echo 'hello'"

#[[block]]
#block = "disk_space"
#path = "/"
#alias = "/"
#info_type = "available"
#unit = "GB"
#interval = 20
#warning = 20.0
#alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 10
format = "{utilization}%"

# [[block]]
# block = "load"
# interval = 1
# format = "{1m}"

[[block]]
block = "sound"
on_click = "pulsemixer --toggle-mute"

# [[block]]
# block = "net"
# device = "wlp0s20f3"
# ssid = false
# ip = false
# speed_up = false
# graph_up = false
# interval = 5

[[block]]
block = "backlight"

[[block]]
block = "battery"

[[block]]
block = "time"
interval = 60
format = "%I:%M"
