# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports = [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix> ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ehci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
    "sr_mod"
    "sdhci_pci"
  ];
  boot.kernelModules = [ "kvm-intel" "wl" ];
  boot.extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];

  boot.initrd.luks.devices = [{
    name = "root";
    device = "/dev/sda4";
    preLVM = true;
  }];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/49295af9-3f85-479d-8ed3-dd83c6a0b4c7";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/67E3-17ED";
    fsType = "vfat";
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/25ff3e4a-553d-4c5b-bd3f-016d6bec63c0"; }];

  nix.maxJobs = lib.mkDefault 8;
}
